# Generate a fresh Docker image containing all the dependencies that
# we need to run the web app (and manage it over SSH).
#
# Usage:
#   docker build . -f Dockerfile_from_scratch -t penelopeysm/apribot && docker push penelopeysm/apribot
#
# After this is done, the main Dockerfile will just pull from this pre-built
# image, meaning that we don't have to re-build the dependencies every time we
# deploy.

FROM python:3.11.4-bookworm

WORKDIR /

# Directories
COPY ./app ./app
COPY ./python ./python
COPY ./static ./static
# Files
COPY ./apribot.cabal .
COPY ./cabal.project .
COPY ./cabal.project.freeze .

# This line circumvents a spurious error with cabal.project's git submodule.
# It should go away if I ever upload reddit-oauth2 to Hackage
RUN git config --global --add safe.directory '*'

# Install sqlite3
RUN apt-get update && apt-get install -y sqlite3

# Install packages
RUN python -m pip install --upgrade pip setuptools && python -m pip install -r python/requirements.txt

# Set up Haskell
# https://stackoverflow.com/a/71513191
RUN curl https://downloads.haskell.org/~ghcup/x86_64-linux-ghcup > /usr/bin/ghcup && chmod +x /usr/bin/ghcup
# discord-haskell doesn't work with GHC 9.6, so we stick to 9.4
RUN ghcup -v install ghc --isolate /usr/local --force 9.4.5 && ghcup -v install cabal --isolate /usr/local/bin --force 3.6.2.0
RUN cabal update
RUN cabal build

CMD ["/bin/bash"]

# vim: ft=dockerfile
