# fly.toml app configuration file generated for apribot on 2023-05-13T18:20:59+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "apribot"
primary_region = "lhr"

[[mounts]]
  source = "apribot_data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
