# fly.toml app configuration file generated for apribot on 2023-06-18T02:13:34+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "apribot"
primary_region = "lhr"

[http_service]
  internal_port = 8080
  force_https = true
