module Natures (getRecommendedNatures) where

import Data.Text (Text)
import qualified Data.Text as T

makeNatureText :: Text -> [(Text, Text)] -> Text
makeNatureText title mons =
  case mons of
    [] -> ""
    ms -> T.unlines ("**" <> title <> "**" : map (\(name, nature) -> "- " <> name <> ": " <> nature) ms)

getRecommendedNatures :: Text -> Text
getRecommendedNatures searchString =
  let s = T.toLower searchString
      p = filter (\(name, _) -> s `T.isInfixOf` name) penny
      jSwsh = filter (\(name, _) -> s `T.isInfixOf` name) jemmaSwSh
      jBdsp = filter (\(name, _) -> s `T.isInfixOf` name) jemmaBdsp
      jG7 = filter (\(name, _) -> s `T.isInfixOf` name) jemmaG7
   in case makeNatureText "Natures in Penny's sheet (mostly from Pikalytics):" p
        <> makeNatureText "Natures in Jemma's SwSh sheet (from Smogon):" jSwsh
        <> makeNatureText "Natures in Jemma's BDSP sheet (from Smogon):" jBdsp
        <> makeNatureText "Natures in Jemma's Gen 7 sheet (from Smogon):" jG7 of
        "" -> "No results found for pokemon '" <> searchString <> "'."
        x -> x

jemmaG7 :: [(Text, Text)]
jemmaG7 =
  [ ("bulbasaur", "Modest"),
    ("charmander", "Timid / Jolly"),
    ("squirtle", "Timid / Modest"),
    ("caterpie", "Timid"),
    ("weedle", "Jolly"),
    ("pidgey", "Jolly"),
    ("rattata", "Jolly"),
    ("rattata-alola", "Jolly / Adamant"),
    ("spearow", "Jolly"),
    ("ekans", "Adamant"),
    ("sandshrew", "Jolly"),
    ("sandshrew-alola", "Jolly"),
    ("nidoran-f", "Timid / Modest"),
    ("nidoran-m", "Timid / Modest"),
    ("vulpix", "Timid"),
    ("vulpix-alola", "Timid"),
    ("zubat", "Jolly"),
    ("oddish", "Bold (V) / Timid (B)"),
    ("paras", "Careful"),
    ("venonat", "Timid"),
    ("diglett", "Adamant / Jolly"),
    ("diglett-alola", "Jolly"),
    ("meowth", "Timid"),
    ("meowth-alola", "Timid"),
    ("psyduck", "Modest"),
    ("mankey", "Jolly"),
    ("growlithe", "Jolly"),
    ("poliwag", "Timid (W) / Calm (T)"),
    ("abra", "Timid"),
    ("machop", "Adamant"),
    ("bellsprout", "Timid / Modest"),
    ("tentacool", "Timid"),
    ("geodude", "Adamant / Jolly"),
    ("geodude-alola", "Jolly"),
    ("ponyta", "Jolly"),
    ("slowpoke", "Bold / Modest (K)"),
    ("magnemite", "Modest / Timid"),
    ("farfetch'd", "Adamant"),
    ("doduo", "Jolly"),
    ("seel", "Calm"),
    ("grimer", "Careful"),
    ("grimer-alola", "Adamant"),
    ("shellder", "Jolly"),
    ("gastly", "Timid"),
    ("onix", "Brave / Impish"),
    ("drowzee", "Jolly"),
    ("krabby", "Adamant / Jolly"),
    ("voltorb", "Jolly / Timid"),
    ("exeggcute", "Quiet (K) / Modest (A)"),
    ("cubone", "Brave (K) / Adamant (A)"),
    ("lickitung", "Calm"),
    ("koffing", "Bold"),
    ("rhyhorn", "Adamant"),
    ("chansey", "Bold"),
    ("tangela", "Sassy"),
    ("kangaskhan", "Jolly"),
    ("horsea", "Modest"),
    ("goldeen", "Adamant"),
    ("staryu", "Timid"),
    ("mr-mime", "Timid"),
    ("scyther", "Impish / Adamant"),
    ("pinsir", "Jolly"),
    ("tauros", "Naive / Adamant"),
    ("magikarp", "Jolly"),
    ("lapras", "Modest"),
    ("eevee", "Timid (E,G,J) / Adamant (F) / Jolly (L) / Bold (S,V) / Calm (U)"),
    ("porygon", "Timid"),
    ("omanyte", "Modest / Timid"),
    ("kabuto", "Jolly"),
    ("aerodactyl", "Jolly"),
    ("snorlax", "Careful"),
    ("dratini", "Jolly"),
    ("chikorita", "Calm"),
    ("cyndaquil", "Timid"),
    ("totodile", "Jolly / Adamant"),
    ("sentret", "Jolly"),
    ("hoothoot", "Modest"),
    ("ledyba", "Jolly"),
    ("spinarak", "Jolly"),
    ("chinchou", "Modest"),
    ("pichu", "Timid"),
    ("cleffa", "Bold"),
    ("igglybuff", "Timid"),
    ("togepi", "Timid"),
    ("natu", "Impish / Modest"),
    ("mareep", "Modest"),
    ("marill", "Adamant"),
    ("sudowoodo", "Adamant"),
    ("hoppip", "Jolly"),
    ("aipom", "Jolly"),
    ("sunkern", "Modest"),
    ("yanma", "Timid"),
    ("wooper", "Relaxed"),
    ("murkrow", "Jolly"),
    ("misdreavus", "Timid"),
    ("wobbuffet", "Bold"),
    ("girafarig", "Jolly"),
    ("pineco", "Jolly"),
    ("dunsparce", "Adamant"),
    ("gligar", "Jolly"),
    ("snubbull", "Adamant"),
    ("qwilfish", "Timid / Jolly"),
    ("shuckle", "Calm"),
    ("heracross", "Adamant / Jolly"),
    ("sneasel", "Jolly"),
    ("teddiursa", "Brave"),
    ("slugma", "Calm"),
    ("swinub", "Adamant / Jolly"),
    ("corsola", "Bold"),
    ("remoraid", "Quiet "),
    ("delibird", "Timid"),
    ("mantine", "Calm"),
    ("skarmory", "Bold"),
    ("houndour", "Timid"),
    ("phanpy", "Adamant"),
    ("stantler", "Lonely / Hasty"),
    ("smeargle", "Jolly"),
    ("tyrogue", "Careful (C) / Adamant (L) / Impish (T)"),
    ("smoochum", "Timid"),
    ("elekid", "Naive / Modest / Jolly"),
    ("magby", "Modest"),
    ("miltank", "Calm"),
    ("larvitar", "Adamant"),
    ("treecko", "Timid"),
    ("torchic", "Jolly / Adamant"),
    ("mudkip", "Adamant / Jolly"),
    ("poochyena", "Adamant / Jolly"),
    ("zigzagoon", "Adamant"),
    ("wurmple", "Bold (D) / Timid (B)"),
    ("lotad", "Modest / Timid"),
    ("seedot", "Lonely / Hasty"),
    ("taillow", "Timid"),
    ("wingull", "Bold"),
    ("ralts", "Timid (V) / Jolly (L)"),
    ("surskit", "Timid"),
    ("shroomish", "Careful"),
    ("slakoth", "Naive"),
    ("nincada", "Jolly (N) / Adamant (S)"),
    ("whismur", "Timid"),
    ("makuhita", "Adamant"),
    ("azurill", "Adamant"),
    ("nosepass", "Modest"),
    ("skitty", "Jolly"),
    ("sableye", "Careful"),
    ("mawile", "Adamant"),
    ("aron", "Careful"),
    ("meditite", "Jolly / Adamant"),
    ("electrike", "Timid"),
    ("plusle", "Timid"),
    ("minun", "Timid"),
    ("volbeat", "Relaxed"),
    ("illumise", "Relaxed"),
    ("roselia", "Timid"),
    ("gulpin", "Quiet"),
    ("carvanha", "Adamant / Jolly"),
    ("wailmer", "Calm"),
    ("numel", "Calm"),
    ("torkoal", "Bold"),
    ("spoink", "Timid"),
    ("spinda", "Brave"),
    ("trapinch", "Jolly"),
    ("cacnea", "Mild"),
    ("swablu", "Adamant"),
    ("zangoose", "Adamant / Jolly"),
    ("seviper", "Naughty"),
    ("lunatone", "Modest / Timid"),
    ("solrock", "Impish"),
    ("barboach", "Jolly"),
    ("corphish", "Jolly"),
    ("baltoy", "Bold"),
    ("lileep", "Bold"),
    ("anorith", "Adamant"),
    ("feebas", "Calm"),
    ("castform", "Timid"),
    ("kecleon", "Adamant"),
    ("shuppet", "Adamant"),
    ("duskull", "Adamant"),
    ("tropius", "Bold"),
    ("chimecho", "Timid"),
    ("absol", "Adamant / Jolly"),
    ("wynaut", "Calm"),
    ("snorunt", "Jolly (G) / Timid (F)"),
    ("spheal", "Calm"),
    ("clamperl", "Modest (G) / Timid (G) / Naughty (H) "),
    ("relicanth", "Adamant"),
    ("luvdisc", "Modest / Timid"),
    ("bagon", "Adamant / Jolly"),
    ("beldum", "Jolly / Adamant"),
    ("turtwig", "Impish"),
    ("chimchar", "Jolly"),
    ("piplup", "Calm"),
    ("starly", "Jolly"),
    ("bidoof", "Adamant"),
    ("kricketot", "Jolly"),
    ("shinx", "Jolly"),
    ("budew", "Timid"),
    ("cranidos", "Jolly"),
    ("shieldon", "Careful"),
    ("burmy", "Rash (M) / Timid (P) / Impish (S) / Careful (T)"),
    ("combee", "Bold"),
    ("pachirisu", "Impish"),
    ("buizel", "Timid"),
    ("cherubi", "Jolly"),
    ("shellos-west", "Sassy"),
    ("shellos-east", "Sassy"),
    ("drifloon", "Modest / Timid"),
    ("buneary", "Jolly"),
    ("glameow", "Jolly"),
    ("chingling", "Calm"),
    ("stunky", "Jolly"),
    ("bronzor", "Calm"),
    ("bonsly", "Adamant"),
    ("mime-jr", "Timid"),
    ("happiny", "Bold"),
    ("chatot", "Timid"),
    ("spiritomb", "Adamant / Brave"),
    ("gible", "Jolly"),
    ("munchlax", "Careful"),
    ("riolu", "Jolly / Adamant"),
    ("hippopotas", "Impish"),
    ("skorupi", "Jolly"),
    ("croagunk", "Jolly"),
    ("carnivine", "Adamant"),
    ("finneon", "Bold"),
    ("mantyke", "Calm"),
    ("snover", "Modest / Mild"),
    ("rotom", "Timid (ALL) / Bold (FAN)"),
    ("phione", "Relaxed"),
    ("snivy", "Timid"),
    ("tepig", "Jolly"),
    ("oshawott", "Timid"),
    ("patrat", "Adamant / Jolly"),
    ("lillipup", "Adamant / Jolly"),
    ("purrloin", "Jolly"),
    ("pansage", "Jolly"),
    ("pansear", "Timid"),
    ("panpour", "Timid"),
    ("munna", "Modest"),
    ("pidove", "Adamant"),
    ("blitzle", "Timid"),
    ("roggenrola", "Careful"),
    ("woobat", "Timid"),
    ("drilbur", "Jolly"),
    ("audino", "Calm"),
    ("timburr", "Adamant"),
    ("tympole", "Timid"),
    ("throh", "Impish / Adamant"),
    ("sawk", "Jolly"),
    ("sewaddle", "Jolly"),
    ("venipede", "Jolly"),
    ("cottonee", "Timid"),
    ("petilil", "Timid"),
    ("basculin-blue", "Naive"),
    ("basculin-red", "Adamant"),
    ("sandile", "Jolly / Adamant"),
    ("darumaka", "Jolly / Adamant"),
    ("maractus", "Naughty"),
    ("dwebble", "Jolly"),
    ("scraggy", "Jolly"),
    ("sigilyph", "Timid"),
    ("yamask", "Quiet"),
    ("tirtouga", "Adamant / Jolly"),
    ("archen", "Naive"),
    ("trubbish", "Impish"),
    ("zorua", "Timid"),
    ("minccino", "Jolly"),
    ("gothita", "Modest"),
    ("solosis", "Quiet / Bold"),
    ("ducklett", "Timid"),
    ("vanillite", "Modest"),
    ("deerling", "Jolly"),
    ("emolga", "Timid"),
    ("karrablast", "Adamant"),
    ("foongus", "Calm / Modest"),
    ("frillish", "Bold"),
    ("alomomola", "Impish"),
    ("joltik", "Timid"),
    ("ferroseed", "Careful / Sassy"),
    ("klink", "Adamant"),
    ("tynamo", "Rash"),
    ("elgyem", "Quiet"),
    ("litwick", "Timid / Modest"),
    ("axew", "Adamant"),
    ("cubchoo", "Adamant"),
    ("cryogonal", "Calm"),
    ("shelmet", "Timid"),
    ("stunfisk", "Bold"),
    ("mienfoo", "Jolly / Naive"),
    ("druddigon", "Adamant"),
    ("golett", "Adamant"),
    ("pawniard", "Adamant"),
    ("bouffalant", "Adamant"),
    ("rufflet", "Careful"),
    ("vullaby", "Bold"),
    ("heatmor", "Rash"),
    ("durant", "Jolly"),
    ("deino", "Modest"),
    ("larvesta", "Timid / Modest"),
    ("chespin", "Impish"),
    ("fennekin", "Timid"),
    ("froakie", "Timid / Hasty"),
    ("bunnelby", "Adamant"),
    ("fletchling", "Jolly"),
    ("scatterbug", "Timid"),
    ("litleo", "Timid"),
    ("flabebe", "Timid"),
    ("flabébé", "Timid"),
    ("skiddo", "Careful"),
    ("pancham", "Adamant"),
    ("furfrou", "Jolly"),
    ("espurr", "Timid (F) / Bold (M)"),
    ("honedge", "Sassy"),
    ("spritzee", "Quiet"),
    ("swirlix", "Adamant / Jolly"),
    ("inkay", "Careful"),
    ("binacle", "Naive / Jolly"),
    ("skrelp", "Modest"),
    ("clauncher", "Modest"),
    ("helioptile", "Timid"),
    ("tyrunt", "Jolly"),
    ("amaura", "Modest / Timid"),
    ("hawlucha", "Adamant"),
    ("dedenne", "Timid"),
    ("carbink", "Relaxed"),
    ("goomy", "Timid / Hasty"),
    ("klefki", "Careful"),
    ("phantump", "Jolly"),
    ("pumpkaboo", "Adamant (A) / Impish (L) / Jolly (SM) / Bold (SU)"),
    ("bergmite", "Impish"),
    ("noibat", "Timid"),
    ("rowlet", "Timid"),
    ("litten", "Jolly"),
    ("popplio", "Modest"),
    ("pikipek", "Rash / Naive"),
    ("yungoos", "Adamant"),
    ("grubbin", "Modest"),
    ("crabrawler", "Adamant"),
    ("oricorio", "Timid"),
    ("cutiefly", "Timid"),
    ("rockruff", "Jolly (B) / Adamant (M)"),
    ("rockruff-dusk", "Jolly"),
    ("wishiwashi", "Quiet"),
    ("mareanie", "Calm"),
    ("mudbray", "Impish"),
    ("dewpider", "Adamant"),
    ("fomantis", "Bold"),
    ("morelull", "Modest"),
    ("salandit", "Timid"),
    ("stufful", "Adamant"),
    ("bounsweet", "Adamant / Jolly"),
    ("comfey", "Modest"),
    ("oranguru", "Quiet"),
    ("passimian", "Jolly"),
    ("wimpod", "Adamant"),
    ("sandygast", "Bold"),
    ("pyukumuku", "Bold"),
    ("minior", "Naughty / Adamant"),
    ("komala", "Adamant"),
    ("turtonator", "Timid"),
    ("togedemaru", "Jolly"),
    ("mimikyu", "Adamant / Jolly"),
    ("bruxish", "Jolly / Adamant"),
    ("drampa", "Modest"),
    ("dhelmise", "Adamant"),
    ("jangmo-o", "Hasty / Jolly")
  ]

jemmaBdsp :: [(Text, Text)]
jemmaBdsp =
  [ ("bulbasaur", "Modest"),
    ("charmander", "Timid"),
    ("squirtle", "Bold / Modest"),
    ("caterpie", "Timid"),
    ("weedle", "Jolly"),
    ("pidgey", "Jolly"),
    ("rattata", "Jolly"),
    ("spearow", "Jolly"),
    ("ekans", "Adamant"),
    ("sandshrew", "Adamant"),
    ("nidoran-f", "Modest"),
    ("nidoran-m", "Timid"),
    ("vulpix", "Timid"),
    ("zubat", "Jolly"),
    ("oddish", "Bold (Vileplume) / Timid (Bellossom)"),
    ("paras", "Careful"),
    ("venonat", "Timid"),
    ("diglett", "Adamant"),
    ("meowth", "Jolly"),
    ("psyduck", "Timid / Modest"),
    ("mankey", "Jolly"),
    ("growlithe", "Jolly"),
    ("poliwag", "Bold (Politoed) / Jolly / Adamant (Poliwrath)"),
    ("abra", "Timid"),
    ("machop", "Adamant"),
    ("bellsprout", "Timid / Modest"),
    ("tentacool", "Timid"),
    ("geodude", "Adamant / Jolly"),
    ("ponyta", "Jolly"),
    ("slowpoke", "Relaxed (Slowbro) / Bold (Slowking)"),
    ("magnemite", "Modest / Bold"),
    ("farfetch'd", "Adamant"),
    ("doduo", "Jolly"),
    ("seel", "Calm"),
    ("grimer", "Careful"),
    ("shellder", "Jolly / Adamant"),
    ("gastly", "Timid"),
    ("onix", "Impish"),
    ("drowzee", "Jolly"),
    ("krabby", "Jolly"),
    ("voltorb", "Jolly / Timid"),
    ("exeggcute", "Modest / Timid / Quiet "),
    ("cubone", "Adamant"),
    ("lickitung", "Careful"),
    ("koffing", "Bold"),
    ("rhyhorn", "Adamant"),
    ("chansey", "Bold"),
    ("tangela", "Sassy / Relaxed"),
    ("kangaskhan", "Adamant / Jolly"),
    ("horsea", "Rash / Naive"),
    ("goldeen", "Jolly / Adamant"),
    ("staryu", "Timid"),
    ("mr-mime", "Timid"),
    ("scyther", "Adamant / Careful"),
    ("pinsir", "Jolly"),
    ("tauros", "Jolly"),
    ("magikarp", "Jolly"),
    ("lapras", "Bold"),
    ("eevee", "Timid (Es / Jo) / Bold (Va) / Careful (Um) / Modest (Gl) / Jolly (Le) / Careful / Calm / Adamant (Fl)"),
    ("porygon", "Timid"),
    ("omanyte", "Modest / Timid"),
    ("kabuto", "Jolly / Adamant"),
    ("aerodactyl", "Jolly"),
    ("snorla", "Adamant / Careful"),
    ("dratini", "Jolly / Adamant"),
    ("chikorita", "Calm"),
    ("cyndaquil", "Timid"),
    ("totodile", "Jolly / Adamant"),
    ("sentret", "Jolly"),
    ("hoothoot", "Modest"),
    ("ledyba", "Jolly"),
    ("spinarak", "Jolly"),
    ("chinchou", "Modest"),
    ("pichu", "Timid"),
    ("cleffa", "Bold / Timid"),
    ("igglybuff", "Calm"),
    ("togepi", "Bold"),
    ("natu", "Bold"),
    ("mareep", "Modest"),
    ("marill", "Adamant"),
    ("sudowoodo", "Adamant / Brave"),
    ("hoppip", "Jolly"),
    ("aipom", "Jolly"),
    ("sunkern", "Modest"),
    ("yanma", "Timid"),
    ("wooper", "Bold"),
    ("murkrow", "Jolly"),
    ("misdreavus", "Timid"),
    ("wobbuffet", "Bold"),
    ("girafarig", "Jolly"),
    ("pineco", "Jolly"),
    ("dunsparce", "Adamant"),
    ("gligar", "Jolly"),
    ("snubbull", "Adamant"),
    ("qwilfish", "Jolly"),
    ("shuckle", "Bold"),
    ("heracross", "Jolly"),
    ("sneasel", "Jolly"),
    ("teddiursa", "Brave"),
    ("slugma", "Calm"),
    ("swinub", "Adamant / Jolly"),
    ("corsola", "Bold"),
    ("remoraid", "Modest"),
    ("delibird", "Jolly"),
    ("mantine", "Bold"),
    ("skarmory", "Impish"),
    ("houndour", "Timid"),
    ("phanpy", "Adamant"),
    ("stantler", "Jolly"),
    ("smeargle", "Jolly"),
    ("tyrogue", "Careful / Adamant / Jolly (chan) / Adamant (lee) / Impish (top)"),
    ("smoochum", "Timid"),
    ("elekid", "Adamant / Jolly"),
    ("magby", "Modest"),
    ("miltank", "Careful"),
    ("larvitar", "Adamant"),
    ("treecko", "Timid"),
    ("torchic", "Adamant / Jolly"),
    ("mudkip", "Jolly / Adamant"),
    ("poochyena", "Adamant / Jolly"),
    ("zigzagoon", "Adamant"),
    ("wurmple", "Bold (Dust) / Timid (Beau)"),
    ("lotad", "Modest"),
    ("seedot", "Adamant"),
    ("taillow", "Timid"),
    ("wingull", "Bold / Modest"),
    ("ralts", "Timid (Gardevoir) / Jolly (Gallade)"),
    ("surskit", "Timid"),
    ("shroomish", "Careful"),
    ("slakoth", "Naive"),
    ("nincada", "Adamant (Ninjask) / Adamant / Jolly (Shedinja)"),
    ("whismur", "Timid / Modest"),
    ("makuhita", "Adamant"),
    ("azurill", "Adamant"),
    ("nosepass", "Modest"),
    ("skitty", "Jolly"),
    ("sableye", "Careful"),
    ("mawile", "Adamant"),
    ("aron", "Careful"),
    ("meditite", "Jolly / Adamant"),
    ("electrike", "Timid"),
    ("plusle", "Timid"),
    ("minun", "Timid"),
    ("volbeat", "Relaxed"),
    ("illumise", "Relaxed"),
    ("roselia", "Timid"),
    ("gulpin", "Quiet"),
    ("carvanha", "Adamant / Jolly"),
    ("wailmer", "Calm"),
    ("numel", "Calm"),
    ("torkoal", "Bold"),
    ("spoink", "Timid"),
    ("spinda", "Brave"),
    ("trapinch", "Jolly"),
    ("cacnea", "Mild"),
    ("swablu", "Calm"),
    ("zangoose", "Adamant / Jolly"),
    ("seviper", "Naughty"),
    ("lunatone", "Timid"),
    ("solrock", "Impish"),
    ("barboach", "Modest"),
    ("corphish", "Adamant / Naughty"),
    ("baltoy", "Calm"),
    ("lileep", "Bold"),
    ("anorith", "Adamant"),
    ("feebas", "Bold"),
    ("castform", "Timid"),
    ("kecleon", "Adamant"),
    ("shuppet", "Adamant"),
    ("duskull", "Adamant"),
    ("tropius", "Bold"),
    ("chimecho", "Timid"),
    ("absol", "Jolly / Adamant"),
    ("wynaut", "Bold"),
    ("snorunt", "Timid "),
    ("spheal", "Adamant"),
    ("clamperl", "Modest / Timid (Gore) / Naughty (Hunt)"),
    ("relicanth", "Adamant"),
    ("luvdisc", "Modest / Timid"),
    ("bagon", "Timid / Jolly / Naive / Impish"),
    ("beldum", "Adamant / Jolly"),
    ("turtwig", "Impish"),
    ("chimchar", "Jolly"),
    ("piplup", "Calm"),
    ("starly", "Jolly"),
    ("bidoof", "Adamant"),
    ("kricketot", "Jolly"),
    ("shin", "Jolly / Adamant"),
    ("budew", "Timid"),
    ("cranidos", "Jolly"),
    ("shieldon", "Careful"),
    ("burmy", "Rash (Moth) / Timid (Plant) / Impish (Sand) / Careful (Trash)"),
    ("combee", "Bold / Impish"),
    ("pachirisu", "Impish"),
    ("buizel", "Timid"),
    ("cherubi", "Timid"),
    ("shellos-west", "Calm / Sassy"),
    ("shellos-east", "Calm / Sassy"),
    ("drifloon", "Bold"),
    ("buneary", "Jolly"),
    ("glameow", "Jolly"),
    ("chingling", "Calm"),
    ("stunky", "Timid / Modest"),
    ("bronzor", "Sassy / Careful"),
    ("bonsly", "Adamant / Brave"),
    ("mime-jr", "Timid"),
    ("happiny", "Bold"),
    ("chatot", "Timid"),
    ("spiritomb", "Adamant / Bold"),
    ("gible", "Jolly / Naive / Hasty"),
    ("munchlax", "Adamant / Careful"),
    ("riolu", "Jolly"),
    ("hippopotas", "Impish"),
    ("skorupi", "Jolly"),
    ("croagunk", "Jolly"),
    ("carnivine", "Adamant"),
    ("finneon", "Bold"),
    ("mantyke", "Bold"),
    ("snover", "Modest / Mild"),
    ("rotom", "Timid")
  ]

jemmaSwSh :: [(Text, Text)]
jemmaSwSh =
  [ ("bulbasaur", "Modest"),
    ("charmander", "Timid"),
    ("squirtle", "Bold / Modest"),
    ("caterpie", "Timid"),
    ("sandshrew", "Adamant"),
    ("sandshrew-alola", "Jolly"),
    ("nidoran-f", "Modest"),
    ("nidoran-m", "Timid"),
    ("vulpix", "Timid"),
    ("vulpix-alola", "Timid"),
    ("zubat", "Jolly"),
    ("oddish", "Bold (Vileplume) / Timid (Bellossom)"),
    ("diglett", "Adamant"),
    ("diglett-alola", "Jolly"),
    ("meowth", "Jolly"),
    ("meowth-alola", "Jolly"),
    ("meowth-galar", "Adamant"),
    ("psyduck", "Timid / Modest"),
    ("growlithe", "Jolly"),
    ("poliwag", "Bold (Politoed) / Jolly / Adamant (Poliwrath)"),
    ("abra", "Timid"),
    ("machop", "Adamant"),
    ("tentacool", "Timid"),
    ("ponyta", "Jolly"),
    ("ponyta-galar", "Jolly / Timid"),
    ("slowpoke", "Relaxed (Slowbro) / Bold (Slowking)"),
    ("slowpoke-galar", "Modest (Slowbro) / Calm (Slowking)"),
    ("magnemite", "Modest / Bold"),
    ("farfetch'd", "Adamant"),
    ("farfetch'd-galar", "Adamant"),
    ("shellder", "Jolly / Adamant"),
    ("gastly", "Timid"),
    ("onix", "Impish"),
    ("krabby", "Jolly"),
    ("exeggcute", "Modest / Timid / Quiet (Kanto) / Modest (Alola)"),
    ("cubone", "Adamant"),
    ("lickitung", "Careful"),
    ("koffing", "Bold"),
    ("rhyhorn", "Adamant"),
    ("chansey", "Bold"),
    ("tangela", "Sassy / Relaxed"),
    ("kangaskhan", "Adamant / Jolly"),
    ("horsea", "Rash / Naive"),
    ("goldeen", "Jolly / Adamant"),
    ("staryu", "Timid"),
    ("mr-mime", "Timid"),
    ("mr-mime-galar", "Timid / Modest / Calm"),
    ("scyther", "Adamant / Careful"),
    ("pinsir", "Jolly"),
    ("tauros", "Jolly"),
    ("magikarp", "Jolly"),
    ("lapras", "Bold"),
    ("eevee", "Timid (Es / Jo) / Bold (Va / Sy) / Careful (Um) / Modest (Gl) / Jolly (Le) / Careful / Calm / Adamant (Fl)"),
    ("porygon", "Timid"),
    ("omanyte", "Modest / Timid"),
    ("kabuto", "Jolly / Adamant"),
    ("aerodactyl", "Jolly"),
    ("snorla", "Adamant / Careful"),
    ("dratini", "Jolly / Adamant"),
    ("hoothoot", "Modest"),
    ("chinchou", "Modest"),
    ("pichu", "Timid"),
    ("cleffa", "Bold / Timid"),
    ("igglybuff", "Calm"),
    ("togepi", "Bold"),
    ("natu", "Bold"),
    ("marill", "Adamant"),
    ("sudowoodo", "Adamant / Brave"),
    ("wooper", "Bold"),
    ("wobbuffet", "Bold"),
    ("dunsparce", "Adamant"),
    ("qwilfish", "Jolly"),
    ("shuckle", "Bold"),
    ("heracross", "Jolly"),
    ("sneasel", "Jolly"),
    ("swinub", "Adamant / Jolly"),
    ("corsola", "Bold"),
    ("corsola-galar", "Timid / Modest"),
    ("remoraid", "Modest"),
    ("delibird", "Adamant"),
    ("mantine", "Bold"),
    ("skarmory", "Impish"),
    ("tyrogue", "Careful / Adamant / Jolly (chan) / Adamant (lee) / Impish (top)"),
    ("smoochum", "Timid"),
    ("elekid", "Adamant / Jolly"),
    ("magby", "Modest"),
    ("miltank", "Calm"),
    ("larvitar", "Adamant"),
    ("treecko", "Timid"),
    ("torchic", "Adamant / Jolly"),
    ("mudkip", "Jolly / Adamant"),
    ("zigzagoon", "Adamant"),
    ("zigzagoon-galar", "Adamant"),
    ("lotad", "Modest"),
    ("seedot", "Adamant"),
    ("wingull", "Bold / Modest"),
    ("ralts", "Timid (Gardevoir) / Jolly (Gallade)"),
    ("nincada", "Adamant (Ninjask) / Adamant / Jolly (Shedinja)"),
    ("whismur", "Timid / Modest"),
    ("azurill", "Adamant"),
    ("sableye", "Careful"),
    ("mawile", "Adamant"),
    ("aron", "Careful"),
    ("electrike", "Timid"),
    ("roselia", "Timid"),
    ("carvanha", "Adamant / Jolly"),
    ("wailmer", "Calm"),
    ("torkoal", "Bold"),
    ("trapinch", "Jolly"),
    ("swablu", "Calm"),
    ("lunatone", "Timid"),
    ("solrock", "Impish"),
    ("barboach", "Modest"),
    ("corphish", "Adamant / Naughty"),
    ("baltoy", "Calm"),
    ("lileep", "Bold"),
    ("anorith", "Adamant"),
    ("feebas", "Bold"),
    ("duskull", "Adamant"),
    ("absol", "Jolly / Adamant"),
    ("wynaut", "Bold"),
    ("snorunt", "Timid "),
    ("spheal", "Adamant"),
    ("relicanth", "Adamant"),
    ("bagon", "Timid / Jolly / Naive / Impish"),
    ("beldum", "Adamant / Jolly"),
    ("shin", "Jolly / Adamant"),
    ("budew", "Timid"),
    ("combee", "Bold / Impish"),
    ("cherubi", "Timid"),
    ("shellos-west", "Calm / Sassy"),
    ("shellos-east", "Calm / Sassy"),
    ("drifloon", "Bold"),
    ("buneary", "Jolly"),
    ("stunky", "Timid / Modest"),
    ("bronzor", "Sassy / Careful"),
    ("bonsly", "Adamant / Brave"),
    ("mime jr.", "Timid"),
    ("happiny", "Bold"),
    ("spiritomb", "Adamant / Bold"),
    ("gible", "Jolly / Naive / Hasty"),
    ("munchla", "Adamant / Careful"),
    ("riolu", "Jolly"),
    ("hippopotas", "Impish"),
    ("skorupi", "Jolly"),
    ("croagunk", "Jolly"),
    ("mantyke", "Bold"),
    ("snover", "Modest / Mild"),
    ("rotom", "Timid"),
    ("lillipup", "Adamant"),
    ("purrloin", "Jolly / Adamant"),
    ("munna", "Bold / Modest"),
    ("pidove", "Jolly"),
    ("roggenrola", "Careful"),
    ("woobat", "Timid"),
    ("drilbur", "Jolly"),
    ("audino", "Careful"),
    ("timburr", "Adamant / Careful"),
    ("tympole", "Relaxed / Adamant"),
    ("throh", "Careful / Adamant"),
    ("sawk", "Jolly"),
    ("venipede", "Adamant / Jolly"),
    ("cottonee", "Timid"),
    ("petilil", "Timid"),
    ("basculin-red", "Naive"),
    ("basculin-blue", "Adamant"),
    ("sandile", "Jolly"),
    ("darumaka", "Jolly"),
    ("darumaka-galar", "Jolly"),
    ("maractus", "Hasty / Mild"),
    ("dwebble", "Jolly"),
    ("scraggy", "Careful"),
    ("sigilyph", "Timid"),
    ("yamask", "Quiet / Modest"),
    ("yamask-galar", "Impish"),
    ("tirtouga", "Naughty / Adamant"),
    ("archen", "Jolly"),
    ("trubbish", "Impish"),
    ("zorua", "Timid"),
    ("minccino", "Jolly"),
    ("gothita", "Bold"),
    ("solosis", "Bold"),
    ("vanillite", "Timid"),
    ("emolga", "Timid"),
    ("karrablast", "Careful"),
    ("foongus", "Bold"),
    ("frillish", "Bold"),
    ("joltik", "Timid"),
    ("ferroseed", "Careful / Sassy"),
    ("klink", "Jolly"),
    ("elgyem", "Bold / Modest / Quiet"),
    ("litwick", "Timid"),
    ("axew", "Jolly"),
    ("cubchoo", "Adamant"),
    ("cryogonal", "Timid"),
    ("shelmet", "Timid"),
    ("stunfisk", "Calm"),
    ("stunfisk-galar", "Careful"),
    ("mienfoo", "Jolly"),
    ("druddigon", "Impish"),
    ("golett", "Adamant"),
    ("pawniard", "Adamant"),
    ("bouffalant", "Adamant"),
    ("rufflet", "Jolly"),
    ("vullaby", "Impish"),
    ("heatmor", "Adamant / Timid / Modest"),
    ("durant", "Jolly"),
    ("deino", "Timid"),
    ("larvesta", "Timid"),
    ("bunnelby", "Adamant"),
    ("fletchling", "Jolly"),
    ("pancham", "Adamant"),
    ("espurr", "Timid"),
    ("honedge", "Adamant"),
    ("spritzee", "Bold"),
    ("swirlix", "Adamant / Jolly"),
    ("inkay", "Careful"),
    ("binacle", "Jolly"),
    ("skrelp", "Modest"),
    ("clauncher", "Modest"),
    ("helioptile", "Timid"),
    ("tyrunt", "Adamant / Jolly"),
    ("amaura", "Modest / Timid"),
    ("hawlucha", "Adamant"),
    ("dedenne", "Timid"),
    ("carbink", "Relaxed"),
    ("goomy", "Timid / Modest"),
    ("klefki", "Careful"),
    ("phantump", "Jolly"),
    ("pumpkaboo-average", "Jolly / Adamant / Naive / Timid"),
    ("pumpkaboo-small", "Jolly / Adamant / Naive / Timid"),
    ("pumpkaboo-large", "Jolly / Adamant / Naive / Timid"),
    ("pumpkaboo-super", "Jolly / Adamant / Naive / Timid"),
    ("bergmite", "Impish"),
    ("noibat", "Timid"),
    ("rowlet", "Timid"),
    ("litten", "Careful"),
    ("popplio", "Modest / Bold"),
    ("grubbin", "Modest"),
    ("cutiefly", "Timid"),
    ("rockruff", "Jolly / Adamant"),
    ("rockruff-dusk", "Jolly"),
    ("wishiwashi", "Bold / Calm"),
    ("mareanie", "Bold / Impish / Relaxed"),
    ("mudbray", "Impish"),
    ("dewpider", "Adamant"),
    ("fomantis", "Bold"),
    ("morelull", "Calm"),
    ("salandit", "Timid"),
    ("stufful", "Jolly"),
    ("bounsweet", "Jolly"),
    ("comfey", "Bold"),
    ("oranguru", "Modest / Quiet / Calm"),
    ("passimian", "Jolly"),
    ("wimpod", "Adamant"),
    ("sandygast", "Bold"),
    ("pyukumuku", "Bold"),
    ("turtonator", "Calm"),
    ("togedemaru", "Jolly"),
    ("mimikyu", "Jolly / Adamant"),
    ("drampa", "Bold / Modest"),
    ("dhelmise", "Adamant"),
    ("jangmo-o", "Bold / Impish / Naive / Jolly / Timid"),
    ("grookey", "Adamant"),
    ("scorbunny", "Jolly / Adamant"),
    ("sobble", "Timid"),
    ("skwovet", "Adamant / Impish"),
    ("rookidee", "Careful / Relaxed / Impish"),
    ("blipbug", "Timid"),
    ("nickit", "Timid"),
    ("gossifleur", "Modest"),
    ("wooloo", "Impish"),
    ("chewtle", "Jolly / Adamant"),
    ("yamper", "Jolly"),
    ("rolycoly", "Adamant"),
    ("applin", "Modest / Bold (Appletun) / Jolly (Flapple)"),
    ("silicobra", "Impish / Careful"),
    ("cramorant", "Timid"),
    ("arrokuda", "Adamant"),
    ("toxel", "Timid / Modest / Rash"),
    ("sizzlipede", "Jolly"),
    ("clobbopus", "Adamant"),
    ("sinistea", "Timid / Modest"),
    ("hatenna", "Bold / Quiet"),
    ("impidimp", "Bold"),
    ("milcery", "Bold"),
    ("falinks", "Jolly / Adamant"),
    ("pincurchin", "Bold / Modest"),
    ("snom", "Timid"),
    ("stonjourner", "Jolly"),
    ("eiscue", "Jolly"),
    ("indeedee-f", "Timid"),
    ("indeedee-m", "Timid"),
    ("morpeko", "Jolly"),
    ("cufant", "Adamant / Careful"),
    ("duraludon", "Timid"),
    ("dreepy", "Timid")
  ]

penny :: [(Text, Text)]
penny =
  [ ("abra", "Timid"),
    ("absol", "Adamant"),
    ("aerodactyl", "Jolly"),
    ("amaura", "Modest"),
    ("anorith", "Adamant"),
    ("applin", "Adamant"),
    ("archen", "Jolly"),
    ("aron", "Adamant"),
    ("arrokuda", "Adamant"),
    ("audino", "Calm"),
    ("axew", "Adamant"),
    ("bagon", "Jolly"),
    ("baltoy", "Bold"),
    ("barboach", "Adamant"),
    ("basculin-blue", "Adamant"),
    ("basculin-red", "Adamant"),
    ("basculin-white", "Adamant"),
    ("beldum", "Adamant"),
    ("bergmite", "Adamant"),
    ("binacle", "Adamant"),
    ("blipbug", "Timid"),
    ("bombirdier", "Adamant"),
    ("bouffalant", "Brave"),
    ("bounsweet", "Adamant"),
    ("bramblin", "Adamant"),
    ("bronzor", "Relaxed"),
    ("bruxish", "Jolly"),
    ("bulbasaur", "Timid"),
    ("buneary", "Jolly"),
    ("bunnelby", "Jolly"),
    ("cacnea", "Adamant"),
    ("capsakid", "Naive"),
    ("carbink", "Relaxed"),
    ("carvanha", "Adamant"),
    ("caterpie", "Timid"),
    ("cetoddle", "Adamant"),
    ("chansey", "Bold"),
    ("charcadet", "Modest/Adamant"),
    ("charmander", "Timid"),
    ("cherubi", "Modest"),
    ("chespin", "Impish"),
    ("chewtle", "Adamant"),
    ("chinchou", "Calm"),
    ("clauncher", "Modest"),
    ("cleffa", "Calm"),
    ("clobbopus", "Careful"),
    ("combee", "Adamant"),
    ("comfey", "Bold/Calm"),
    ("corphish", "Adamant"),
    ("corsola", "Bold"),
    ("corsola-galar", "Quiet"),
    ("cottonee", "Timid"),
    ("crabrawler", "Adamant"),
    ("cramorant", "Adamant"),
    ("croagunk", "Adamant"),
    ("cryogonal", "Timid"),
    ("cubchoo", "Jolly"),
    ("cubone", "Adamant"),
    ("cufant", "Brave"),
    ("cutiefly", "Timid"),
    ("cyclizar", "Jolly"),
    ("darumaka", "Jolly"),
    ("darumaka-galar", "Jolly"),
    ("dedenne", "Jolly"),
    ("deerling", "Jolly"),
    ("deino", "Modest"),
    ("delibird", "Jolly"),
    ("dewpider", "Brave"),
    ("dhelmise", "Brave"),
    ("diglett", "Jolly"),
    ("diglett-alola", "Jolly"),
    ("dondozo", "Adamant/Jolly"),
    ("drampa", "Modest"),
    ("dratini", "Adamant"),
    ("dreepy", "Jolly"),
    ("drifloon", "Timid"),
    ("drilbur", "Adamant"),
    ("druddigon", "Impish"),
    ("dunsparce", "Adamant"),
    ("duraludon", "Modest"),
    ("durant", "Jolly"),
    ("duskull", "Sassy"),
    ("dwebble", "Adamant"),
    ("eevee", "Modest"),
    ("eiscue", "Adamant/Jolly"),
    ("electrike", "Timid"),
    ("elekid", "Adamant"),
    ("elgyem", "Quiet"),
    ("emolga", "Timid"),
    ("espurr", "Timid"),
    ("exeggcute", "Quiet"),
    ("falinks", "Adamant"),
    ("farfetch'd", "Adamant"),
    ("farfetch'd-galar", "Adamant"),
    ("feebas", "Bold/Calm"),
    ("ferroseed", "Relaxed"),
    ("fidough", "Impish"),
    ("finizen", "Jolly"),
    ("flabebe-blue", "Calm"),
    ("flabebe-orange", "Calm"),
    ("flabebe-red", "Calm"),
    ("flabebe-white", "Calm"),
    ("flabebe-yellow", "Calm"),
    ("flabébé-blue", "Calm"),
    ("flabébé-orange", "Calm"),
    ("flabébé-red", "Calm"),
    ("flabébé-white", "Calm"),
    ("flabébé-yellow", "Calm"),
    ("flamigo", "Jolly"),
    ("fletchling", "Jolly"),
    ("flittle", "Timid"),
    ("fomantis", "Brave"),
    ("foongus", "Relaxed/Sassy"),
    ("frigibax", "Adamant"),
    ("frillish", "Calm"),
    ("froakie", "Timid"),
    ("fuecoco", "Modest"),
    ("gastly", "Timid"),
    ("gible", "Jolly"),
    ("glimmet", "Timid"),
    ("goldeen", "Careful"),
    ("golett", "Adamant"),
    ("goomy", "Modest"),
    ("gossifleur", "Bold"),
    ("gothita", "Jolly/Impish"),
    ("greavard", "Adamant"),
    ("grookey", "Adamant"),
    ("growlithe", "Jolly/Timid"),
    ("grubbin", "Quiet"),
    ("hatenna", "Quiet"),
    ("hawlucha", "Adamant"),
    ("heatmor", "Modest"),
    ("helioptile", "Timid"),
    ("heracross", "Adamant"),
    ("hippopotas", "Impish"),
    ("honedge", "Quiet"),
    ("hoothoot", "Modest"),
    ("horsea", "Timid/Jolly"),
    ("igglybuff", "Modest"),
    ("illumise", "Timid"),
    ("impidimp", "Careful"),
    ("indeedee-f", "Bold/Relaxed"),
    ("indeedee-m", "Bold/Relaxed"),
    ("inkay", "Adamant"),
    ("jangmo-o", "Bold/Modest"),
    ("joltik", "Timid"),
    ("kabuto", "Jolly"),
    ("kangaskhan", "Jolly"),
    ("karrablast", "Brave"),
    ("kecleon", "Careful"),
    ("klawf", "Impish"),
    ("klefki", "Bold"),
    ("klink", "Jolly"),
    ("koffing", "Timid"),
    ("komala", "Adamant"),
    ("krabby", "Adamant"),
    ("kricketot", "Adamant"),
    ("lapras", "Calm"),
    ("larvesta", "Timid"),
    ("larvitar", "Adamant"),
    ("lechonk", "Impish"),
    ("lickitung", "Impish"),
    ("lileep", "Modest"),
    ("lillipup", "Jolly"),
    ("litten", "Careful/Impish"),
    ("litwick", "Modest"),
    ("lotad", "Modest"),
    ("lunatone", "Modest"),
    ("machop", "Adamant"),
    ("magby", "Timid"),
    ("magikarp", "Jolly"),
    ("magnemite", "Modest"),
    ("mantine", "Modest"),
    ("maractus", "Bold"),
    ("mareanie", "Calm"),
    ("marill", "Adamant"),
    ("maschiff", "Adamant"),
    ("mawile", "Adamant"),
    ("meowth", "Jolly"),
    ("meowth-alola", "Timid"),
    ("meowth-galar", "Adamant"),
    ("mienfoo", "Jolly"),
    ("milcery", "Bold"),
    ("miltank", "Impish"),
    ("mimikyu", "Jolly"),
    ("minccino", "Jolly"),
    ("minun", "Timid"),
    ("morelull", "Sassy"),
    ("morpeko", "Jolly"),
    ("mr. mime", "Relaxed"),
    ("mr. mime-galar", "Quiet"),
    ("mudbray", "Brave"),
    ("mudkip", "Adamant"),
    ("munna", "Relaxed"),
    ("nacli", "Relaxed"),
    ("natu", "Timid"),
    ("nickit", "Timid"),
    ("nidoran-f", "Timid"),
    ("nidoran-m", "Timid"),
    ("nincada", "Adamant"),
    ("noibat", "Timid"),
    ("nosepass", "Calm"),
    ("nymble", "Jolly"),
    ("oddish", "Modest"),
    ("omanyte", "Modest"),
    ("onix", "Brave"),
    ("oranguru", "Sassy"),
    ("oricorio", "Timid"),
    ("orthworm", "Impish"),
    ("pachirisu", "Impish"),
    ("pancham", "Adamant"),
    ("passimian", "Adamant"),
    ("pawmi", "Jolly"),
    ("pawniard", "Adamant"),
    ("petilil", "Timid"),
    ("phantump", "Brave"),
    ("pichu", "Timid"),
    ("pidove", "Adamant"),
    ("pincurchin", "Quiet"),
    ("pinsir", "Jolly"),
    ("piplup", "Modest"),
    ("plusle", "Timid"),
    ("poliwag", "Calm"),
    ("ponyta", "Jolly"),
    ("ponyta-galar", "Jolly"),
    ("popplio", "Modest"),
    ("porygon", "Sassy/Timid"),
    ("psyduck", "Timid"),
    ("pumpkaboo-average", "Jolly"),
    ("pumpkaboo-large", "Relaxed"),
    ("pumpkaboo-small", "Jolly"),
    ("pumpkaboo-super", "Relaxed"),
    ("purrloin", "Jolly"),
    ("pyukumuku", "Calm"),
    ("quaxly", "Adamant"),
    ("qwilfish", "Adamant"),
    ("ralts", "Timid/Adamant"),
    ("relicanth", "Adamant"),
    ("rellor", "Quiet"),
    ("remoraid", "Modest"),
    ("rhyhorn", "Brave"),
    ("riolu", "Jolly"),
    ("rockruff", "Jolly"),
    ("rockruff-dusk", "Jolly"),
    ("roggenrola", "Brave"),
    ("rolycoly", "Modest"),
    ("rookidee", "Careful"),
    ("roselia", "Timid"),
    ("rotom", "Modest"),
    ("rowlet", "Adamant"),
    ("rufflet", "Jolly"),
    ("sableye", "Careful"),
    ("salandit", "Timid"),
    ("sandile", "Jolly"),
    ("sandshrew", "Adamant"),
    ("sandshrew-alola", "Adamant"),
    ("sandygast", "Quiet"),
    ("sawk", "Jolly"),
    ("scatterbug", "Timid"),
    ("scorbunny", "Jolly"),
    ("scraggy", "Careful"),
    ("scyther", "Adamant"),
    ("seedot", "Jolly"),
    ("shellder", "Jolly"),
    ("shellos-east", "Bold"),
    ("shellos-west", "Bold"),
    ("shelmet", "Timid"),
    ("shinx", "Jolly"),
    ("shroodle", "Careful"),
    ("shuckle", "Relaxed"),
    ("sigilyph", "Timid"),
    ("silicobra", "Careful"),
    ("sinistea", "Timid"),
    ("sizzlipede", "Adamant"),
    ("skarmory", "Impish"),
    ("skiddo", "Adamant"),
    ("skitty", "Jolly"),
    ("skorupi", "Jolly"),
    ("skrelp", "Modest"),
    ("skwovet", "Adamant"),
    ("slowpoke", "Relaxed"),
    ("slowpoke-galar", "Relaxed"),
    ("smoliv", "Modest"),
    ("smoochum", "Timid"),
    ("sneasel", "Jolly"),
    ("snom", "Modest"),
    ("snorlax", "Sassy"),
    ("snorunt", "Impish"),
    ("snover", "Quiet"),
    ("snubbull", "Impish"),
    ("sobble", "Timid"),
    ("solosis", "Quiet"),
    ("solrock", "Adamant"),
    ("spheal", "Calm"),
    ("spiritomb", "Relaxed"),
    ("sprigatito", "Jolly"),
    ("spritzee", "Relaxed"),
    ("squawkabilly-blue", "Jolly"),
    ("squawkabilly-green", "Jolly"),
    ("squawkabilly-white", "Jolly"),
    ("squawkabilly-yellow", "Jolly"),
    ("squirtle", "Calm/Modest"),
    ("staryu", "Timid"),
    ("stonjourner", "Adamant"),
    ("stufful", "Adamant"),
    ("stunfisk", "Calm"),
    ("stunfisk-galar", "Impish"),
    ("stunky", "Jolly"),
    ("sudowoodo", "Brave"),
    ("swablu", "Calm"),
    ("swinub", "Adamant/Jolly"),
    ("swirlix", "Timid"),
    ("tadbulb", "Bold"),
    ("tandemaus", "Jolly"),
    ("tangela", "Sassy"),
    ("tarountula", "Relaxed/Sassy"),
    ("tatsugiri-curly", "Modest"),
    ("tatsugiri-droopy", "Modest"),
    ("tatsugiri-stretchy", "Modest"),
    ("tauros", "Jolly"),
    ("tauros-aqua", "Jolly"),
    ("tauros-blaze", "Jolly"),
    ("tauros-combat", "Jolly"),
    ("tentacool", "Calm"),
    ("throh", "Adamant"),
    ("timburr", "Adamant"),
    ("tinkatink", "Adamant"),
    ("tirtouga", "Adamant"),
    ("toedscool", "Bold/Calm"),
    ("togedemaru", "Jolly"),
    ("togepi", "Modest/Timid/Calm/Bold (mostly Modest)"),
    ("torchic", "Adamant"),
    ("torkoal", "Quiet"),
    ("toxel", "Modest"),
    ("trapinch", "Jolly"),
    ("treecko", "Timid"),
    ("trubbish", "Adamant"),
    ("turtonator", "Quiet"),
    ("tympole", "Adamant"),
    ("tynamo", "Quiet"),
    ("tyrogue", "Adamant/Careful"),
    ("tyrunt", "Adamant"),
    ("vanillite", "Timid"),
    ("varoom", "Jolly"),
    ("veluza", "Adamant"),
    ("venipede", "Jolly"),
    ("volbeat", "Timid"),
    ("vullaby", "Calm"),
    ("vulpix", "Timid"),
    ("vulpix-alola", "Timid"),
    ("wailmer", "Modest"),
    ("wattrel", "Timid"),
    ("whismur", "Modest"),
    ("wiglett", "Jolly"),
    ("wimpod", "Adamant"),
    ("wingull", "Modest/Timid"),
    ("wishiwashi", "Brave"),
    ("wobbuffet", "Calm"),
    ("woobat", "Timid"),
    ("wooloo", "Impish"),
    ("wooper", "Relaxed"),
    ("wooper-paldea", "Careful"),
    ("yamask", "Relaxed"),
    ("yamask-galar", "Relaxed"),
    ("yamper", "Timid"),
    ("yungoos", "Brave"),
    ("zigzagoon", "Jolly"),
    ("zigzagoon-galar", "Jolly"),
    ("zorua", "Jolly"),
    ("zorua-hisui", "Timid"),
    ("zubat", "Jolly")
  ]
